### ISSUE TITLE
AWSの勉強

### ISSUE THREAD

**Issue by tomoyuki-nakabayashi** [tomoyuki-nakabayashi/MyPlayGround#7]
**AWSによるサーバレスアーキテクチャ**をやる。

ソースコードはここ。
https://github.com/sbarski/serverless-architectures-aws

**Comment by tomoyuki-nakabayashi** [comment]
過去にAWSアカウントを停止してしまっていた。
サポートフォームから再開を申請中。

**Comment by tomoyuki-nakabayashi** [comment]
付録Bのインストールとセットアップをやる。

**Comment by tomoyuki-nakabayashi** [comment]
aws-cliをインストールする。

```
https://docs.aws.amazon.com/ja_jp/streams/latest/dev/kinesis-tutorial-cli-installation.html
```

```
$ curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
$ sudo python get-pip.py
$ sudo pip install awscli
```

```
$ aws help
AWS()                                                                    AWS()



NAME
       aws -

DESCRIPTION
       The  AWS  Command  Line  Interface is a unified tool to manage your AWS
       services.

SYNOPSIS
...
```

**Comment by tomoyuki-nakabayashi** [comment]
IAM (Identity and Access Management) を設定する。

**Comment by tomoyuki-nakabayashi** [comment]
最初のlambdaを作成し、ローカルでテストする。
index.jsがあるディレクトリで次を実行する。

```
npm install run-local-lambda --save-dev
```

**Comment by tomoyuki-nakabayashi** [comment]
なんか文句を言われたので、言われた通りやってみる。

```
┌────────────────────────────────────────────────────────────┐
│                  npm update check failed                   │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) /home/tomoyuki/.config │
└────────────────────────────────────────────────────────────┘
```

**Comment by tomoyuki-nakabayashi** [comment]
```
$ npm test
Error: Cannot find module 'aws-sdk'
```

ムムム？

```
$ ls node_modules/
```

にaws-sdkがない。

```
$ npm install aws-sdk
```

```
$ npm test
> transcode-video@1.0.0 test /home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video
> run-local-lambda --file index.js --event tests/event.json

key: my video.mp4 my video.mp4 my video
{ errorMessage: 'User: arn:aws:iam::998535819267:user/lambda-upload is not authorized to perform: elastictranscoder:CreateJob on resource: arn:aws:elastictranscoder:us-east-1:998535819267:pipeline/1530966437207-utqiym',
  errorType: 'AccessDeniedException',
  stack: 'AccessDeniedException: User: arn:aws:iam::998535819267:user/lambda-upload is not authorized to perform: elastictranscoder:CreateJob on resource: arn:aws:elastictranscoder:us-east-1:998535819267:pipeline/1530966437207-utqiym\n    at Object.extractError (/home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video/node_modules/aws-sdk/lib/protocol/json.js:48:27)\n    at Request.extractError (/home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)\n    at Request.callListeners (/home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit (/home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video/node_modules/aws-sdk/lib/request.js:685:12)' }
```

OK!

**Comment by tomoyuki-nakabayashi** [comment]
package.jsonのscriptsにdeployとpredeployを追加する。
npm run deploy時に実行するスクリプトをここに書けるらしい。

```
$ npm run deploy
> transcode-video@1.0.0 deploy /home/tomoyuki/work/07.PlayGround/MyPlayGround/Serverless/transcode-video
> aws lambda update-function-code --function-name  arn:aws:lambda:us-east-1:998535819267:function:transcode-video --zip-file fileb://Lambda-Deployment.zip

{
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "CodeSha256": "t0Cm/aecZC/7VjM9pvYInLfzWq9BzhxYQwy4+Ud6Ul8=",
    "FunctionName": "transcode-video",
    "CodeSize": 5432714,
    "RevisionId": "b2463bde-a752-4d39-a539-4d800445eca3",
    "MemorySize": 128,
    "FunctionArn": "arn:aws:lambda:us-east-1:998535819267:function:transcode-video",
    "Version": "$LATEST",
    "Role": "arn:aws:iam::998535819267:role/lambda-s3-execution-role",
    "Timeout": 3,
    "LastModified": "2018-07-08T11:06:42.280+0000",
    "Handler": "index.handler",
    "Runtime": "nodejs6.10",
    "Description": ""
}
```

OK！

**Comment by tomoyuki-nakabayashi** [comment]
AWS Lambdaで動作確認する。

できたぁ！

**Comment by tomoyuki-nakabayashi** [comment]
あ、serverless-video-transcoded-nkbじゃなくて、severlessになっている…。ひどいtypoだ…。

**Comment by tomoyuki-nakabayashi** [comment]
https://www.johnvansickle.com/ffmpeg/

ffmpegのスタティックビルドを使う。

**Comment by tomoyuki-nakabayashi** [comment]
26M  7月 10 20:34 Lambda-Deployment.zip

26MBか。ffprobeが61MBなのにけっこう小さくなるもんだ。

**Comment by tomoyuki-nakabayashi** [comment]
3章が一通り終わった。けっこうGUIでポチポチしないといけないのが面倒だが、簡単にできるな。

**Comment by tomoyuki-nakabayashi** [comment]
演習問題は一旦お預けで、前に進もう。

**Comment by tomoyuki-nakabayashi** [comment]
4章はセキュリティ、ログ、アラート、課金、全て重要だな！

**Comment by tomoyuki-nakabayashi** [comment]
pp.86 ポリシーのバージョンに2018が含まれているとダメらしい？なんで？

かならず、2012-10-17を指定しないといけないらしい。あっそ。

**Comment by tomoyuki-nakabayashi** [comment]
仮想マシンを切ってしまった…。明日デプロイテストをしよう。

**Comment by tomoyuki-nakabayashi** [comment]
第2部第5章

- API Gateway
- Auth0

このあたりのことがわかるようだ。

**Comment by tomoyuki-nakabayashi** [comment]
Amazon Cognitoも知りたかったが、これは範囲外か…。

**Comment by tomoyuki-nakabayashi** [comment]
少し付録Cに寄り道。認証と認可について。

**Comment by tomoyuki-nakabayashi** [comment]
うーん、ちょっと認証周りの説明がちゃんと理解できていないな。作ってから一旦戻ってくる必要がありそうだ。

**Comment by tomoyuki-nakabayashi** [comment]
webサイトをホスティングするのに、local-web-serverモジュールが利用できる。

```
npm install local-web-server --save-dev
```

```js
  "scripts": {
    "start": "ws",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

package.jsonに↑のように書いて、npm startでweb serverが起動する。あとはブラウザでアクセスすればよい。

**Comment by tomoyuki-nakabayashi** [comment]
html5のローカルストレージ機能を使っている。
過去に1度でもtokenを保存してあれば、local storageからデータをリストアする。

```js
    var idToken = localStorage.getItem('userToken');

    if (idToken) {
      this.configureAuthenticatedRequests();
      this.data.auth0Lock.getProfile(idToken, function(err, profile) {
        if (err) {
          return alert('There was an error getting the profile: ' + err.message);
        }
        that.showUserAuthenticationDetails(profile);
      });
    }
```

**Comment by tomoyuki-nakabayashi** [comment]
今後、HTTPリクエストを出すときに、HTTPリクエストのAuthorizationヘッダーにtokenが組み込まれる、と。

```js
  configureAuthenticatedRequests: function() {
    $.ajaxSetup({
      'beforeSend': function(xhr) {
        xhr.setRequestHeader('Authorization', 'Bearer ' + localStorage.getItem('userToken'));
      }
    });
  },
```

**Comment by tomoyuki-nakabayashi** [comment]
よしよし。

![image](https://user-images.githubusercontent.com/20079103/42729751-6a1a9c0e-881d-11e8-91eb-dbd06b1b82a7.png)

**Comment by tomoyuki-nakabayashi** [comment]
sign upもlog inもできないが？と思ったら、auth0にアカウントは作られている？

**Comment by tomoyuki-nakabayashi** [comment]
うーん？パスワード変更とかはできるぞ。ページからうまくリクエストを遅れていない？

**Comment by tomoyuki-nakabayashi** [comment]
やっとできた…。

auth0の設定でAllowed Web Originsを設定しないとダメみたい。しょーもな…。

**Comment by tomoyuki-nakabayashi** [comment]
ログアウトボタンにトグルしないんだよなぁ。気になるが、少し先に進めるか。

**Comment by tomoyuki-nakabayashi** [comment]
Auth0のAPIバージョンの9が使えなくなっているのか…。

**Comment by tomoyuki-nakabayashi** [comment]
https://auth0.com/docs/libraries/lock/v11

ここを参考に作り替えよう。

```js
<script src="https://cdn.auth0.com/js/lock/11.6.1/lock.min.js"></script>
<script>
  var lock = new Auth0Lock('XT8qlbyX4sKkJpjb8QMvprEZmuQ345T5', 't-nakabayashi.auth0.com', {
    auth: {
      redirectUrl: 'http://127.0.0.1:8000',
      responseType: 'code',
      params: {
        scope: 'openid email' // Learn about scopes: https://auth0.com/docs/scopes
      }
    }
  });
</script>
<button onclick="lock.show();">Login</button>
```

**Comment by tomoyuki-nakabayashi** [comment]
https://github.com/sbarski/serverless-architectures-aws/issues/9

issueもあがっているな。

**Comment by tomoyuki-nakabayashi** [comment]
変更箇所

newするときにパラメータを指定しろ、とのことなので、APIリファレンス通りに設定する。

```js
    this.data.auth0Lock = new Auth0Lock(config.auth0.clientId, config.auth0.domain, {
      auth: {
        redirectUrl: 'http://127.0.0.1:8000',
        responseType: 'code',
        params: {
          scope: 'openid email user_metadata picture' // Learn about scopes: https://auth0.com/docs/scopes
        }
      }
    });
```

ユーザー情報を取得するAPIが、getProfile()からgetUserInfo()に変更されている。

```js
    if (idToken) {
      this.configureAuthenticatedRequests();
      this.data.auth0Lock.getUserInfo(idToken, function(err, profile) {
```

show()でエラーハンドリングするのではなく、on()でイベントを処理するAPI仕様になっている。
show()は呼び出しだけを行っており、on()の"authenticated"イベントでログイン処理を実行する。

```js
    this.data.auth0Lock.on("authenticated", function(authResult) {
      that.data.auth0Lock.getUserInfo(authResult.accessToken, function(error, profile) {
        that.data.auth0Lock.hide();
        if (error) return alert("Auth0 error:" + error);

        localStorage.setItem("userToken", authResult.accessToken);
        that.configureAuthenticatedRequests();
        that.showUserAuthenticationDetails(profile);
      })
    });

    this.uiElements.loginButton.click(function(e) {
      that.data.auth0Lock.show({
        auth: {
          params: {
              responseType: 'id_token token'
          }
        }
      });
    });
```

**Comment by tomoyuki-nakabayashi** [comment]
curlだと返ってくるね。lambdaでこれが返せればいいわけだ。

```
curl --request GET   --url 'https://t-nakabayashi.auth0.com/userinfo'   --header 'Authorization: Bearer  {CLIENT_SECRET}'   --header 'Content-Type: application/json'
{"sub":"auth0|5b4aa9c4a177ac1965fd94dd","nickname":"hoge","name":"hoge@hotmail.com","picture":"https://s.gravatar.com/avatar/6211b8e523369e03e6e33da45fde1c7e?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fch.png","updated_at":"2018-07-15T05:00:04.537Z","email":"hoge@hotmail.com","email_verified":true}
```

**Comment by tomoyuki-nakabayashi** [comment]
やっと進んだ。長かった。

$.getの返り値がよくわからん。あとで調べておこう。

**Comment by tomoyuki-nakabayashi** [comment]
結局、↓で言っている通りで、トークンを両方送らないとダメなんでしょう。問題はどうやって両方送るか、なんだが。

```
Seems like the userToken from the book is split up into idToken and accessToken.

I tried to go with one of them, but it didn't work.

You need the idToken to do the jwt.verify in the user-profile lambda function.

The POST /tokeninfo endpoind of Auth0 seems to be gone and now you need to use GET /userinfo to get the profile information. This call needs to have the accessToken inside the Authorization header.

So I sent both tokens to the user-profile lambda, one for auth, one for userinfo.
```

**Comment by tomoyuki-nakabayashi** [comment]
$なんとかってjQueryの関数なのか。

$.get()は次のような感じなので、data部分にidTokenを埋め込んであげれば良い？
後は、Lambdaでどうやって取得できるか、か。

http://semooh.jp/jquery/api/ajax/jQuery.get/+url,+data,+callback+/

ちゃんと見ると↓に書いてありそう。bodyで渡すならpostだよなぁ。クエリパラメータで渡すか？

https://docs.aws.amazon.com/ja_jp/apigateway/latest/developerguide/integrating-api-with-aws-services-lambda.html

**Comment by tomoyuki-nakabayashi** [comment]
付録EにAPI Gatewayのマッピングについて書いてある。GETメソッドのクエリパラメータで追加してみよう。

**Comment by tomoyuki-nakabayashi** [comment]
カスタムリクエストヘッダー、そういうのもあるのか

**Comment by tomoyuki-nakabayashi** [comment]
https://auth0.com/docs/integrations/aws/tokens

delegationか。POSTのbodyでid_tokenを投げているな。access tokenは？
